name: Extract Text from PDF

on:
  push:
    paths:
      - '*.pdf' # Trigger workflow on PDF file changes

jobs:
  extract_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Extract Text from PDF
      run: |
        for pdf_file in *.pdf; do
          text_file="${pdf_file%.*}.txt"
          tesseract "$pdf_file" "$text_file" -l eng
        done

    - name: Display Extracted Text
      run: |
        cat *.txt | head -c 2000

    - name: Upload Text Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extracted-text
        path: '*.txt'
