name: Extract Text from PDF

on:
  push:
    paths:
      - 'pdf/**/*.pdf' # Trigger workflow on any push event, but only for PDF files inside the pdf folder

jobs:
  extract_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Tesseract OCR and Poppler
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr poppler-utils

    - name: List PDF files
      id: list-pdf
      run: |
        pdf_files=$(find pdf/ -type f -name '*.pdf' -not -path "pdf-to-txt/*")
        echo "::set-output name=pdf_files::$pdf_files"

    - name: Process PDF files
      run: |
        for pdf_file in ${{ steps.list-pdf.outputs.pdf_files }}; do
          # Extract base name of PDF file without extension
          pdf_basename=$(basename -- "$pdf_file")
          pdf_name="${pdf_basename%.*}"

          # Create output folder for each PDF file
          output_folder="pdf-to-txt/$pdf_name"
          mkdir -p "$output_folder"

          # Convert PDF to images
          pdftoppm -png "$pdf_file" "$output_folder/page"

          # Process each image with Tesseract OCR
          for image_file in "$output_folder"/*.png; do
            text_file="${image_file%.*}.txt"
            tesseract "$image_file" "$text_file" -l eng
          done
        done

    - name: Display Extracted Text
      run: |
        cat pdf-to-txt/**/*.txt | head -c 2000

    - name: Upload Text Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-to-txt-output
        path: 'pdf-to-txt/**/*.txt'
