name: Process Text File

on:
  push:
    paths:
      - '*.txt' # Trigger workflow on text file changes

jobs:
  process_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read Text File
      id: read-text
      run: |
        echo "::set-output name=content::$(cat text.txt)"

    - name: Modify Text
      id: modify-text
      run: |
        echo "${{ steps.read-text.outputs.content }}" | tr '[:lower:]' '[:upper:]' > output.txt

    - name: Display Modified Text
      run: cat output.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: processed-text
        path: output.txt
