name: Extract Text from PDF

on:
  push:

jobs:
  extract_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr poppler-utils

    - name: List PDF files
      id: list-pdf
      run: |
        pdf_files=$(find . -type f -name '*.pdf')
        echo "::set-output name=pdf_files::$pdf_files"

    - name: Process PDF files
      run: |
        for pdf_file in ${{ steps.list-pdf.outputs.pdf_files }}; do
          output_folder="${pdf_file%.*}_images"
          mkdir -p "$output_folder"
          pdftoppm -png "$pdf_file" "$output_folder/page"
          for image_file in "$output_folder"/*.png; do
            text_file="${image_file%.*}.txt"
            tesseract "$image_file" "$text_file" -l eng
          done
        done

    - name: Display Extracted Text
      run: |
        cat **/*.txt | head -c 2000

    - name: Upload Text Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extracted-text
        path: '**/*.txt'
