name: Extract Text from PDF

on:
  push:
    paths:
      - '*.pdf' # Trigger workflow on PDF file changes

jobs:
  extract_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Convert PDF to Images
      run: |
        for pdf_file in *.pdf; do
          output_folder="${pdf_file%.*}_images"
          mkdir -p "$output_folder"
          pdftoppm -png "$pdf_file" "$output_folder/page"
        done

    - name: Extract Text from Images
      run: |
        for image_file in *_images/*.png; do
          text_file="${image_file%.*}.txt"
          tesseract "$image_file" "$text_file" -l eng
        done

    - name: Display Extracted Text
      run: |
        cat *_images/*.txt | head -c 2000

    - name: Upload Text Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extracted-text
        path: '*_images/*.txt'
